"""add strategy_type to trades

Revision ID: 282921ef1d25
Revises: c5d60c075fda
Create Date: 2026-05-25 04:15:56.223316
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '282921ef1d25'
down_revision: Union[str, None] = 'c5d60c075fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('strategy_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'strategy_type')
    # ### end Alembic commands ###
